# Generated by Django 3.2.9 on 2022-02-02 07:43

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_or_file', models.FileField(upload_to='landing_page_assets')),
            ],
        ),
        migrations.CreateModel(
            name='LeadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=60, unique=True)),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('page_banner', models.ImageField(blank=True, null=True, upload_to='page_banner')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('sub_heading', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('title_tag', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('twitter_description', models.TextField(blank=True, null=True)),
                ('twitter_title', models.CharField(blank=True, max_length=260, null=True)),
                ('twitter_image', models.ImageField(blank=True, null=True, upload_to='twitter_images')),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('og_type', models.CharField(blank=True, max_length=260, null=True)),
                ('og_url', models.URLField(blank=True, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og_images')),
                ('parent_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_childs', to='cms_app.page')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('table_with_tech', 'Table With Tech'), ('table_with_services', 'Table With Services'), ('table_with_sercices_2', 'Table With Services 2'), ('heading_logo_border_by_6', 'Heading Logo Border By 6'), ('call_to_action2', 'Call To Action 2'), ('image_with_cards_by_2', 'Image With Cards By 2'), ('testimonials', 'Testimonials'), ('cards_3', 'Cards 3'), ('cards_3_container_fluid', 'Cards 3 Container Fluid'), ('cards_4', 'Cards 4'), ('cards_4_with_link', 'Cards 4 With Link'), ('all_logos', 'All Logos'), ('col_sm_3', 'Col sm 3'), ('col_sm_3_bg_white', 'Col sm 3 Bg White'), ('col_sm_4', 'Col sm 4'), ('col_sm_4_bg_white', 'Col sm 4 Bg White'), ('col_sm_4_with_link', 'Col sm 4 with link'), ('col_sm_4_bg_white_with_link', 'Col sm 4 white with link'), ('img_heading_descrip', 'Image heading descriptin'), ('video_with_full_container', 'Video With Full Container'), ('video_with_description_by_2', 'Video With Description By 2'), ('video_with_description_by_3', 'Video With Description By 3'), ('image_with_description', 'Image With Description'), ('heading_border_name_by_4', 'Heading Border Name By 4'), ('heading_descrip_container', ' Heading Descrip Container'), ('heading_icon_short_descrip_name_border_container_by_4', 'Heading icon short descrip name border container by 4'), ('heading_icon_border_name_by_3', 'Heading Icon Border Name By 3'), ('heading_icon_border_name_by_4', 'Heading Icon Border Name By 4'), ('heading_icon_name_border_container_by_4', 'Heading Icon Name Border Container By 4'), ('heading_icon_name_border_container_by_6', 'Heading Icon Name Border Container By 6'), ('heading_icon_name_short_descrip_without_border_container_by_3', 'Heading Icon Name Short Descrip Without Border Container by 3'), ('heading_img_by_3', 'Heading img by 3'), ('heading_logo_name_border_container_by_6', 'Heading logo name border container by 6'), ('heading_logo_name_short_descrip_border_container_by_3', 'Heading logo name short descrip border container by 3'), ('heading_logo_name_short_descrip_with_border_container_by_4', 'Heading logo name short descrip with border container by 4'), ('heading_media_with_border_container_by_2', 'Heading media with border container by 2'), ('heading_media_without_border_container_by_2', 'Heading media without border container by 2'), ('heading_social_media_container_by_2', 'Heading social media container by 2'), ('heading_sub_heading_icon_media_by_3', 'Heading sub heading icon media by 3'), ('slider', 'Slider'), ('heading_short_des_svg_png_video_2', 'heading short descrip with svg or videos'), ('lead_data_form', 'Lead Data Form')], max_length=200)),
                ('heading', models.CharField(max_length=255)),
                ('sub_heading', models.TextField(blank=True, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='section_backgrounds')),
                ('ordering', models.IntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_app.page')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='VideosUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=300, null=True)),
                ('sub_heading', models.TextField(blank=True, null=True)),
                ('embed_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_urls', to='cms_app.section')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_heading', models.TextField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='cms_app.section')),
            ],
        ),
        migrations.CreateModel(
            name='ImageWithDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_type', models.CharField(choices=[('container', 'Container'), ('container-fluid', 'Container Fluid')], default='container', max_length=20)),
                ('image_alignment', models.CharField(choices=[('left', 'Left Image'), ('right', 'Right Image')], default='left', max_length=10)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='item_backgrounds')),
                ('photo', models.ImageField(upload_to='')),
                ('heading', models.CharField(max_length=255)),
                ('sub_heading', models.TextField(blank=True, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description')),
                ('target_url', models.URLField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_with_description', to='cms_app.section')),
            ],
        ),
        migrations.CreateModel(
            name='IconWithHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=275, null=True)),
                ('sub_heading', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(upload_to='')),
                ('target_url', models.URLField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icon_with_heading', to='cms_app.section')),
            ],
        ),
        migrations.CreateModel(
            name='HeadingWithMultipleImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heading_with_multiple_image_upload', to='cms_app.section')),
            ],
        ),
        migrations.CreateModel(
            name='HeadingWithDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('sub_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description')),
                ('target_url', models.URLField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heading_with_description', to='cms_app.section')),
            ],
        ),
        migrations.CreateModel(
            name='HeadingLogoNameShortDescrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('sub_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_icon', models.ImageField(blank=True, null=True, upload_to='logo_icons')),
                ('short_description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description')),
                ('target_url', models.URLField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heading_logo_name_short_descrip', to='cms_app.section')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answere', models.TextField(blank=True, null=True)),
                ('ordering', models.IntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_faqs', to='cms_app.section')),
            ],
        ),
    ]
