# Generated by Django 3.1.4 on 2020-12-22 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_banner', models.ImageField(upload_to='page_banner')),
                ('heading', models.CharField(max_length=255)),
                ('sub_heading', models.TextField(blank=True, null=True)),
                ('page', models.CharField(choices=[('Home', 'home'), ('About', 'about'), ('Web', 'web_developmet'), ('Backend', 'backend_development'), ('Front', 'frontend_development'), ('Cms', 'cms'), ('Digmarketing', 'digital_marketing'), ('Gads', 'google_ads'), ('Seo', 'seo'), ('Smediaads', 'social_media_ads'), ('Proadcontent', 'promotional_ad_content'), ('Landpgdev', 'landing_page_development'), ('Ecommerce', 'ecommerce'), ('Efromscretch', 'ecommerce_from_scretch'), ('Sconsultation', 'startup_consultation'), ('Wordwoo', 'wordpress&woocommerce'), ('Shopify', 'shopify'), ('Ganalytics', 'google_analytics'), ('Contentdev', 'content_development'), ('Smediacon', 'social_media_content'), ('Awritting', 'article_writting'), ('Preview', 'product_review'), ('Restate', 'real_estate'), ('Classistance', 'cloud_assistance'), ('Amlearning', 'ai&ml_development'), ('Apdev', 'apps_development'), ('Uiux', 'ui/ux')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_heading', models.TextField(blank=True, null=True)),
                ('ordering', models.IntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_app.page')),
            ],
        ),
        migrations.CreateModel(
            name='ImageWithDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_app.section')),
            ],
        ),
        migrations.CreateModel(
            name='IconWithName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_app.section')),
            ],
        ),
        migrations.CreateModel(
            name='IconWithMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='')),
                ('short_description', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_app.section')),
            ],
        ),
        migrations.CreateModel(
            name='IconShortDescriptionWithName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
                ('short_description', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_app.section')),
            ],
        ),
        migrations.CreateModel(
            name='HeadingWithDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_app.section')),
            ],
        ),
        migrations.CreateModel(
            name='CardWithLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo_icon', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_app.section')),
            ],
        ),
    ]
