# Generated by Django 3.1.7 on 2022-04-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0002_auto_20220419_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='headinglogonameshortdescrip',
            name='button_alignment',
            field=models.CharField(choices=[('left', 'Button Left'), ('center', 'Button Center'), ('right', 'Button Right')], default='left', max_length=55),
        ),
        migrations.AddField(
            model_name='headinglogonameshortdescrip',
            name='button_size',
            field=models.CharField(choices=[('small', 'Small Button'), ('large', 'Large Button')], default='small', max_length=55),
        ),
        migrations.AddField(
            model_name='headinglogonameshortdescrip',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
