# Generated by Django 3.2.9 on 2022-02-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0002_leaddata_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headinglogonameshortdescrip',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
