# Generated by Django 3.2.9 on 2022-02-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0003_alter_headinglogonameshortdescrip_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headingwithdescription',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagewithdescription',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
