# Generated by Django 3.1.7 on 2022-04-20 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0004_auto_20220420_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headinglogonameshortdescrip',
            old_name='button_alignment',
            new_name='button_allignment',
        ),
    ]
