# Generated by Django 3.1.4 on 2020-12-29 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0005_auto_20201229_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardwithlogo',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items1', to='cms_app.section'),
        ),
        migrations.AlterField(
            model_name='headingwithdescription',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items6', to='cms_app.section'),
        ),
        migrations.AlterField(
            model_name='iconshortdescriptionwithname',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items5', to='cms_app.section'),
        ),
        migrations.AlterField(
            model_name='iconwithmedia',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items3', to='cms_app.section'),
        ),
        migrations.AlterField(
            model_name='iconwithname',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items4', to='cms_app.section'),
        ),
        migrations.AlterField(
            model_name='imagewithdescription',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items2', to='cms_app.section'),
        ),
    ]
