# Generated by Django 3.1.4 on 2020-12-31 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0006_auto_20201229_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardwithlogo',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_with_logo', to='cms_app.section'),
        ),
        migrations.AlterField(
            model_name='headingwithdescription',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heading_with_description', to='cms_app.section'),
        ),
        migrations.AlterField(
            model_name='iconshortdescriptionwithname',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icon_short_description_with_name', to='cms_app.section'),
        ),
        migrations.AlterField(
            model_name='iconwithmedia',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icon_with_media', to='cms_app.section'),
        ),
        migrations.AlterField(
            model_name='iconwithname',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icon_with_name', to='cms_app.section'),
        ),
        migrations.AlterField(
            model_name='imagewithdescription',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_with_description', to='cms_app.section'),
        ),
    ]
