# Generated by Django 3.1.7 on 2022-03-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0006_auto_20220323_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headinglogonameshortdescrip',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='headingwithdescription',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagewithdescription',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
