# Generated by Django 3.1.7 on 2022-04-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0006_remove_headinglogonameshortdescrip_button_allignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='headinglogonameshortdescrip',
            name='button_direction',
            field=models.CharField(choices=[('left', 'Button Left'), ('center', 'Button Center'), ('right', 'Button Right')], default='left', max_length=15),
        ),
    ]
