# Generated by Django 3.1.4 on 2021-01-06 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0007_auto_20201231_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetConsultWithGetConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('button', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LogoWithName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icon_with_name', to='cms_app.section')),
            ],
        ),
        migrations.AddField(
            model_name='iconshortdescriptionwithname',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iconwithmedia',
            name='heading',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardwithlogo',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='headingwithdescription',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iconshortdescriptionwithname',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iconwithmedia',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iconwithmedia',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagewithdescription',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('web_developmet', 'Web Development'), ('backend_development', 'Backend Development '), ('frontend_development', 'Frontend Development '), ('cms', 'Cms'), ('digital_marketing', 'Digital Marketing'), ('google_ads', 'Google Ads'), ('seo', 'SEO'), ('social_media_ads', 'Social Media Ads'), ('promotional_ad_content', 'Promotional Ad content'), ('landing_page_development', 'Landing Page Development'), ('ecommerce', 'Ecommerce'), ('ecommerce_from_scretch', 'Ecommerce From Scretch'), ('startup_consultation', 'StartUp Consultation'), ('wordpress&woocommerce', 'Wordpress & Woocommerce'), ('shopify', 'Shopify'), ('google_analytics', 'Google Analytics'), ('content_development', 'Content Development'), ('social_media_content', 'Social Media Content'), ('article_writting', 'Article Writting'), ('product_review', 'Product Review'), ('real_estate', 'Real Estate'), ('cloud_assistance', 'Cloud Assistance'), ('ai&ml_development', 'AI & ML Development'), ('apps_development', 'Apps Development'), ('uiux', 'UI/UX')], max_length=255),
        ),
        migrations.DeleteModel(
            name='IconWithName',
        ),
    ]
