# Generated by Django 3.1.7 on 2022-04-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0007_headinglogonameshortdescrip_button_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headinglogonameshortdescrip',
            name='button_direction',
        ),
        migrations.RemoveField(
            model_name='headinglogonameshortdescrip',
            name='button_size',
        ),
        migrations.RemoveField(
            model_name='headinglogonameshortdescrip',
            name='button_text',
        ),
    ]
