# Generated by Django 3.1.7 on 2022-04-03 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0009_auto_20220331_1259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeadData',
        ),
    ]
