# Generated by Django 3.1.4 on 2021-01-08 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0009_auto_20210106_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadingWithMultipleImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('sub_heading', models.TextField(blank=True, null=True)),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='IconWithName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_heading', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='GetConsultWithGetConnect',
        ),
        migrations.AddField(
            model_name='headinglogonameshortdescrip',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='headingwithdescription',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagewithdescription',
            name='container_type',
            field=models.CharField(choices=[('container', 'Container'), ('container_fluid', 'Container Fluid')], default='container', max_length=20),
        ),
        migrations.AddField(
            model_name='imagewithdescription',
            name='image_alignment',
            field=models.CharField(choices=[('left', 'Left Image'), ('right', 'Right Image')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='imagewithdescription',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('top_banner_image', 'Top banner image'), ('get_cnslt_&_get_connect', 'Get Consult & get Connect'), ('heading_border_name_container_by_4', ' Heading Border name container'), ('heading_descrip_border_icon_name_container_by_3', 'Heading descrip border icon name container 3'), ('heading_descrip_container', 'Heading description container '), ('heading_icon_border_name_by_4', ' Heading icon border name 4'), ('heading_icon_name_border_container_by_4', 'Heading icon name border container 4 '), ('heading_icon_name_border_container_by_6', ' Heading icon name border container 6'), ('heading_icon_name_container_by_4', '  Heading icon name container 4'), ('heading_icon_name_short_descrip_without_border_container_by_3', 'Heading icon name short description without border container 3'), ('heading_icon_short_descrip_name_border_container_by_4', 'Heading icon short description name border container 4'), ('heading_img_by_3', 'Heading image 3'), ('heading_lft_cards_rght_image_container_by_2', 'Heading left cards right image container 2'), ('heading_logo_name_border_container_by_6', 'Heading logo name border container 6'), ('heading_logo_name_short_descrip_border_container_5', 'Heading logo name short description border container 5'), ('heading_logo_name_short_descrip_with_border_container_3', 'Heading logo name short description with border container 3'), ('heading_logo_name_short_descrip_with_border_container_by_4', ' Heading logo name short description with border container 4'), ('heading_media_with_border_container_by_2', 'Heading media with border container 2'), ('heading_media_without_border_container_by_2', 'Heading media without border container 2'), ('heading_name_short_descrip_border_container_by_4', 'Heading name short description border container 4'), ('heading_ol_list_by_2', 'Heading ol list 2 '), ('heading_social_media_container_by_2', 'Heading social media container 2'), ('heading_sub_heading_icon_media_by_3', 'Heading sub heading icon media 3'), ('heading_subheading_icon_border_name_by_3', ' Heading sub heading icon border name 3'), ('heading_subheading_icon_name_border_container_by_4', 'Heading sub heading icon name border container 4'), ('heading_subheading_lft_img_rght_img_container_by_2', 'Heading sub heading left image right image container 2'), ('heading_subheading', 'Heading sub heading'), ('heaing_list_by_2', 'Heaing list 2'), ('lft_descrip_rght_img_container_fluid', ''), ('lft_descrip_rght_img_container', 'Left description right image container'), ('lft_descrip_with_bckground_color_rght_img_container_by_2', 'Left description with bckground color right image container 2'), ('lft_heading_rght_descrip_container_by_2', 'Left heading right description container 2'), ('lft_img_rght_descrip_container_fluid', 'Left image right description container fluid'), ('lft_img_rght_descrip_container', 'Left image right description container'), ('lft_img_rght_img_container_fluid_by_2', 'Left image right image container fluid 2')], max_length=200),
        ),
        migrations.DeleteModel(
            name='LogoWithName',
        ),
        migrations.AddField(
            model_name='iconwithname',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icon_with_name', to='cms_app.section'),
        ),
        migrations.AddField(
            model_name='headingwithmultipleimageupload',
            name='Section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heading_with_multiple_image_upload', to='cms_app.section'),
        ),
    ]
