# Generated by Django 3.1.7 on 2022-04-03 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0010_delete_leaddata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagewithdescription',
            name='button_text',
        ),
    ]
