# Generated by Django 3.1.7 on 2022-06-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0011_auto_20220531_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='headinglogonameshortdescrip',
            name='button_direction',
            field=models.CharField(choices=[('left_button', 'Button Left'), ('center_button', 'Button Center'), ('right_button', 'Button Right')], default='left_button', max_length=15),
        ),
        migrations.AddField(
            model_name='headinglogonameshortdescrip',
            name='button_size',
            field=models.CharField(choices=[('small', 'Small Button'), ('large', 'Large Button')], default='small', max_length=55),
        ),
        migrations.AddField(
            model_name='headinglogonameshortdescrip',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
