# Generated by Django 3.1.4 on 2021-01-10 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0012_auto_20210109_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconWithHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_heading', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(upload_to='')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icon_with_name', to='cms_app.section')),
            ],
        ),
        migrations.RemoveField(
            model_name='headinglogonameshortdescrip',
            name='name',
        ),
        migrations.RemoveField(
            model_name='headingwithmultipleimageupload',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='headingwithmultipleimageupload',
            name='sub_heading',
        ),
        migrations.DeleteModel(
            name='IconWithName',
        ),
    ]
