# Generated by Django 3.1.4 on 2021-01-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0014_auto_20210111_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='heading',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
