# Generated by Django 3.1.4 on 2021-01-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0015_auto_20210111_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='heading',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
