# Generated by Django 3.1.7 on 2022-04-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0015_auto_20220403_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='headinglogonameshortdescrip',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='headingwithdescription',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagewithdescription',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
