# Generated by Django 3.1.4 on 2021-01-11 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0016_auto_20210111_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iconwithheading',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icon_with_heading', to='cms_app.section'),
        ),
    ]
