# Generated by Django 3.1.7 on 2022-04-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0019_auto_20220403_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeadData',
        ),
    ]
