# Generated by Django 3.1.4 on 2021-01-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0019_auto_20210112_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headingwithmultipleimageupload',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='headingwithmultipleimageupload',
            name='sub_heading',
        ),
        migrations.AlterField(
            model_name='headingwithmultipleimageupload',
            name='photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
