# Generated by Django 3.1.4 on 2021-01-11 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0020_auto_20210112_0343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headingwithmultipleimageupload',
            old_name='Section',
            new_name='section',
        ),
    ]
