# Generated by Django 3.1.4 on 2021-01-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0021_auto_20210112_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagewithdescription',
            name='container_type',
            field=models.CharField(choices=[('container', 'Container'), ('container-fluid', 'Container Fluid')], default='container', max_length=20),
        ),
    ]
