# Generated by Django 3.1.5 on 2021-01-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0023_auto_20210114_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page',
        ),
        migrations.AddField(
            model_name='page',
            name='page_name',
            field=models.CharField(default=1, max_length=60, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_banner',
            field=models.ImageField(blank=True, null=True, upload_to='page_banner'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
