# Generated by Django 3.1.5 on 2021-01-15 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0024_auto_20210115_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='parent_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms_app.page'),
        ),
    ]
