# Generated by Django 3.1.5 on 2021-01-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0027_auto_20210116_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
