# Generated by Django 3.1.5 on 2021-02-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0028_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='section_backgrounds'),
        ),
        migrations.AlterField(
            model_name='imagewithdescription',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='item_backgrounds'),
        ),
    ]
