# Generated by Django 3.1.5 on 2021-02-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0030_auto_20210206_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_or_file', models.FileField(upload_to='landing_page_assets')),
            ],
        ),
    ]
