# Generated by Django 3.1.5 on 2021-02-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0031_landingpageassets'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageassets',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
