# Generated by Django 3.1.5 on 2021-02-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0032_landingpageassets_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='og_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='og_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='og_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='og_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
