# Generated by Django 3.1.7 on 2021-03-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0033_auto_20210225_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='og_image_url',
        ),
        migrations.AddField(
            model_name='page',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='og_images'),
        ),
    ]
