# Generated by Django 3.1.7 on 2021-03-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0034_auto_20210303_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlidersWithHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_1', models.ImageField(upload_to='')),
                ('photo_2', models.ImageField(upload_to='')),
                ('photo_3', models.ImageField(upload_to='')),
                ('photo_4', models.ImageField(upload_to='')),
                ('photo_5', models.ImageField(upload_to='')),
                ('heading', models.CharField(blank=True, max_length=155, null=True)),
                ('paragraph', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
