# Generated by Django 3.1.7 on 2021-03-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0035_sliderswithheading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sliderswithheading',
            old_name='paragraph',
            new_name='caption',
        ),
    ]
