# Generated by Django 3.1.7 on 2021-03-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0039_auto_20210313_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title_tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
