# Generated by Django 3.1.7 on 2021-04-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0040_page_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagewithdescription',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
