# Generated by Django 3.1.7 on 2021-04-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0041_auto_20210410_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagewithdescription',
            name='photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
