# Generated by Django 3.2.4 on 2021-06-28 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0046_alter_imagewithdescription_sub_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iconwithheading',
            name='heading',
            field=models.CharField(blank=True, max_length=275, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('table_with_tech', 'Table With Tech'), ('table_with_services', 'Table With Services'), ('table_with_sercices_2', 'Table With Services 2'), ('heading_logo_border_by_6', 'Heading Logo Border By 6'), ('book_an_appointment', 'Book An Appointment'), ('call_to_action', 'Call To Action'), ('call_to_action2', 'Call To Action 2'), ('image_with_cards_by_2', 'Image With Cards By 2'), ('testimonials', 'Testimonials'), ('video_with_full_container', 'Video With Full Container'), ('video_with_description_by_2', 'Video With Description By 2'), ('video_with_description_by_3', 'Video With Description By 2'), ('image_with_description', 'Image With Description'), ('heading_border_name_by_4', 'Heading Border Name By 4'), ('heading_descrip_container', ' Heading Descrip Container'), ('heading_icon_short_descrip_name_border_container_by_4', 'Heading Icon Short Descrip Name Border Container By 4'), ('heading_icon_border_name_by_3', 'Heading Icon Border Name By 3'), ('heading_icon_border_name_by_4', 'Heading Icon Border Name By 4'), ('heading_icon_name_border_container_by_4', 'Heading Icon Name Border Container By 4'), ('heading_icon_name_border_container_by_6', 'Heading Icon Name Border Container By 6'), ('heading_icon_name_container_by_4', 'Heading Icon Name Container By 4'), ('heading_icon_name_short_descrip_without_border_container_by_3', 'Heading Icon Name Short Descrip Without Border Container by 3'), ('heading_img_by_3', 'Heading img by 3'), ('heading_logo_name_border_container_by_6', 'Heading logo name border container by 6'), ('heading_logo_name_short_descrip_border_container_by_3', 'Heading logo name short descrip border container by 3'), ('heading_logo_name_short_descrip_with_border_container_by_4', 'Heading logo name short descrip with border container by 4'), ('heading_logo_name_short_descrip_with_border_container_by_5', 'Heading logo name short descrip with border container by 5'), ('heading_media_with_border_container_by_2', 'Heading media with border container by 2'), ('heading_media_without_border_container_by_2', 'Heading media without border container by 2'), ('heading_social_media_container_by_2', 'Heading social media container by 2'), ('heading_sub_heading_icon_media_by_3', 'Heading sub heading icon media by 3'), ('slider', 'Slider'), ('heading_short_des_svg_png_video_2', 'heading short descrip with svg or videos')], max_length=200),
        ),
        migrations.CreateModel(
            name='VideosUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=300, null=True)),
                ('sub_heading', models.TextField(blank=True, null=True)),
                ('embed_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_urls', to='cms_app.section')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answere', models.TextField(blank=True, null=True)),
                ('ordering', models.IntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_faqs', to='cms_app.section')),
            ],
        ),
    ]
