# Generated by Django 3.2.4 on 2021-06-03 06:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0046_alter_imagewithdescription_sub_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagewithdescription',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
