# Generated by Django 3.2.4 on 2021-06-29 10:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0047_auto_20210628_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headingwithdescription',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='imagewithdescription',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
