# Generated by Django 3.2.4 on 2021-06-03 07:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0047_alter_imagewithdescription_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headinglogonameshortdescrip',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Short_description'),
        ),
        migrations.AlterField(
            model_name='headingwithdescription',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
