# Generated by Django 3.2.4 on 2021-06-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0048_auto_20210603_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headinglogonameshortdescrip',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
