# Generated by Django 3.2.4 on 2021-06-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0050_alter_section_section_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideosUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=225)),
                ('embed_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
