# Generated by Django 3.2.4 on 2021-06-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0051_videosurls'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosurls',
            name='sub_heading',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videosurls',
            name='heading',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
