# Generated by Django 3.2.4 on 2021-06-08 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0053_auto_20210608_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosurls',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_urls', to='cms_app.section'),
        ),
    ]
