# Generated by Django 3.2.4 on 2021-06-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0054_alter_videosurls_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosurls',
            name='heading',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
