# Generated by Django 3.1.5 on 2021-01-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(related_name='blog_posts', to='blog.Category'),
        ),
    ]
