# Generated by Django 3.2 on 2021-04-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210218_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_og_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_og_image',
            field=models.ImageField(blank=True, null=True, upload_to='og_images'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_og_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_og_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_title_tag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_twitter_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_twitter_image',
            field=models.ImageField(blank=True, null=True, upload_to='twitter_images'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_twitter_title',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
