# Generated by Django 3.2 on 2021-04-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210428_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_og_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_og_images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_twitter_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_twitter_images'),
        ),
    ]
