# Generated by Django 3.2 on 2021-05-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210430_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_og_type',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_og_image',
            field=models.ImageField(blank=True, null=True, upload_to='og_images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_twitter_image',
            field=models.ImageField(blank=True, null=True, upload_to='twitter_images'),
        ),
    ]
