# Generated by Django 3.2 on 2021-05-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210506_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
