# Generated by Django 3.2 on 2021-05-31 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_publish_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='publish_at',
        ),
    ]
