# Generated by Django 3.2 on 2021-05-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blog_publish_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
