name: Deploy on softopark.com
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo systemctl stop gunicorn
            cd softopark_cms5
            git pull
            sudo systemctl start gunicorn